[[imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"
[[mounts]]
source = "content"
target = "content"
[[mounts]]
source = "assets/img/content"
target = "content"
[[mounts]]
source = "assets/ext"
target = "static/ext"
